// Enum to define acceptable file types for the Dropzone component
export enum AcceptFileType {
  AllImages = "image/*",
  Jpg = "image/jpg",
  Jpeg = "image/jpeg",
  Png = "image/png",
  Svg = "image/svg+xml",
  Gif = "image/gif",
  Webp = "image/webp",
  Images = `${AcceptFileType.Jpg}, ${AcceptFileType.Jpeg}, ${AcceptFileType.Png}, ${AcceptFileType.Svg}`,
  Pdf = "application/pdf",
  Word = "application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  Excel = "application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  PowerPoint = "application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation",
  Text = "text/plain",
  Video = "video/*",
  Zip = "application/zip, application/x-rar-compressed, application/x-7z-compressed",
  Csv = "text/csv",
  AllAudios = "audio/*",
  Mp3 = "audio/mpeg",
  Wav = "audio/wav",
  Ogg = "audio/ogg",
  M4a = "audio/x-m4a",
  Flac = "audio/flac",
  Aac = "audio/aac",
  Wma = "audio/x-ms-wma",
  Audio = `${AcceptFileType.AllAudios}`,
  Audios = `${AcceptFileType.Mp3}, ${AcceptFileType.Wav}, ${AcceptFileType.Ogg}`,
  AllFiles = "*/*",
}
