export const languageOptions = [
  {'id': 'ab', 'title': 'Abkhaz', 'nativeTitle': 'аҧсуа'},
  {'id': 'aa', 'title': 'Afar', 'nativeTitle': 'Afaraf'},
  {'id': 'af', 'title': 'Afrikaans', 'nativeTitle': 'Afrikaans'},
  {'id': 'ak', 'title': 'Akan', 'nativeTitle': 'Akan'},
  {'id': 'sq', 'title': 'Albanian', 'nativeTitle': 'Shqip'},
  {'id': 'am', 'title': 'Amharic', 'nativeTitle': 'አማርኛ'},
  {'id': 'ar', 'title': 'Arabic', 'nativeTitle': 'العربية'},
  {'id': 'an', 'title': 'Aragonese', 'nativeTitle': 'Aragonés'},
  {'id': 'hy', 'title': 'Armenian', 'nativeTitle': 'Հայերեն'},
  {'id': 'as', 'title': 'Assamese', 'nativeTitle': 'অসমীয়া'},
  {'id': 'av', 'title': 'Avaric', 'nativeTitle': 'авар мацӀ, магӀарул мацӀ'},
  {'id': 'ae', 'title': 'Avestan', 'nativeTitle': 'avesta'},
  {'id': 'ay', 'title': 'Aymara', 'nativeTitle': 'aymar aru'},
  {'id': 'az', 'title': 'Azerbaijani', 'nativeTitle': 'azərbaycan dili'},
  {'id': 'bm', 'title': 'Bambara', 'nativeTitle': 'bamanankan'},
  {'id': 'ba', 'title': 'Bashkir', 'nativeTitle': 'башҡорт теле'},
  {'id': 'eu', 'title': 'Basque', 'nativeTitle': 'euskara, euskera'},
  {'id': 'be', 'title': 'Belarusian', 'nativeTitle': 'Беларуская'},
  {'id': 'bn', 'title': 'Bengali', 'nativeTitle': 'বাংলা'},
  {'id': 'bh', 'title': 'Bihari', 'nativeTitle': 'भोजपुरी'},
  {'id': 'bi', 'title': 'Bislama', 'nativeTitle': 'Bislama'},
  {'id': 'bs', 'title': 'Bosnian', 'nativeTitle': 'bosanski jezik'},
  {'id': 'br', 'title': 'Breton', 'nativeTitle': 'brezhoneg'},
  {'id': 'bg', 'title': 'Bulgarian', 'nativeTitle': 'български език'},
  {'id': 'my', 'title': 'Burmese', 'nativeTitle': 'ဗမာစာ'},
  {'id': 'ca', 'title': 'Catalan; Valencian', 'nativeTitle': 'Català'},
  {'id': 'ch', 'title': 'Chamorro', 'nativeTitle': 'Chamoru'},
  {'id': 'ce', 'title': 'Chechen', 'nativeTitle': 'нохчийн мотт'},
  {'id': 'ny', 'title': 'Chichewa; Chewa; Nyanja', 'nativeTitle': 'chiCheŵa, chinyanja'},
  {'id': 'zh', 'title': 'Chinese', 'nativeTitle': '中文 (Zhōngwén), 汉语, 漢語'},
  {'id': 'cv', 'title': 'Chuvash', 'nativeTitle': 'чӑваш чӗлхи'},
  {'id': 'kw', 'title': 'Cornish', 'nativeTitle': 'Kernewek'},
  {'id': 'co', 'title': 'Corsican', 'nativeTitle': 'corsu, lingua corsa'},
  {'id': 'cr', 'title': 'Cree', 'nativeTitle': 'ᓀᐦᐃᔭᐍᐏᐣ'},
  {'id': 'hr', 'title': 'Croatian', 'nativeTitle': 'hrvatski'},
  {'id': 'cs', 'title': 'Czech', 'nativeTitle': 'česky, čeština'},
  {'id': 'da', 'title': 'Danish', 'nativeTitle': 'dansk'},
  {'id': 'dv', 'title': 'Divehi; Dhivehi; Maldivian;', 'nativeTitle': 'ދިވެހި'},
  {'id': 'nl', 'title': 'Dutch', 'nativeTitle': 'Nederlands, Vlaams'},
  {'id': 'en', 'title': 'English', 'nativeTitle': 'English'},
  {'id': 'eo', 'title': 'Esperanto', 'nativeTitle': 'Esperanto'},
  {'id': 'et', 'title': 'Estonian', 'nativeTitle': 'eesti, eesti keel'},
  {'id': 'ee', 'title': 'Ewe', 'nativeTitle': 'Eʋegbe'},
  {'id': 'fo', 'title': 'Faroese', 'nativeTitle': 'føroyskt'},
  {'id': 'fj', 'title': 'Fijian', 'nativeTitle': 'vosa Vakaviti'},
  {'id': 'fi', 'title': 'Finnish', 'nativeTitle': 'suomi, suomen kieli'},
  {'id': 'fr', 'title': 'French', 'nativeTitle': 'français, langue française'},
  {'id': 'ff', 'title': 'Fula; Fulah; Pulaar; Pular', 'nativeTitle': 'Fulfulde, Pulaar, Pular'},
  {'id': 'gl', 'title': 'Galician', 'nativeTitle': 'Galego'},
  {'id': 'ka', 'title': 'Georgian', 'nativeTitle': 'ქართული'},
  {'id': 'de', 'title': 'German', 'nativeTitle': 'Deutsch'},
  {'id': 'el', 'title': 'Greek, Modern', 'nativeTitle': 'Ελληνικά'},
  {'id': 'gn', 'title': 'Guaraní', 'nativeTitle': 'Avañeẽ'},
  {'id': 'gu', 'title': 'Gujarati', 'nativeTitle': 'ગુજરાતી'},
  {'id': 'ht', 'title': 'Haitian; Haitian Creole', 'nativeTitle': 'Kreyòl ayisyen'},
  {'id': 'ha', 'title': 'Hausa', 'nativeTitle': 'Hausa, هَوُسَ'},
  {'id': 'he', 'title': 'Hebrew (modern)', 'nativeTitle': 'עברית'},
  {'id': 'hz', 'title': 'Herero', 'nativeTitle': 'Otjiherero'},
  {'id': 'hi', 'title': 'Hindi', 'nativeTitle': 'हिन्दी, हिंदी'},
  {'id': 'ho', 'title': 'Hiri Motu', 'nativeTitle': 'Hiri Motu'},
  {'id': 'hu', 'title': 'Hungarian', 'nativeTitle': 'Magyar'},
  {'id': 'ia', 'title': 'Interlingua', 'nativeTitle': 'Interlingua'},
  {'id': 'id', 'title': 'Indonesian', 'nativeTitle': 'Bahasa Indonesia'},
  {'id': 'ie', 'title': 'Interlingue', 'nativeTitle': 'Originally called Occidental; then Interlingue after WWII'},
  {'id': 'ga', 'title': 'Irish', 'nativeTitle': 'Gaeilge'},
  {'id': 'ig', 'title': 'Igbo', 'nativeTitle': 'Asụsụ Igbo'},
  {'id': 'ik', 'title': 'Inupiaq', 'nativeTitle': 'Iñupiaq, Iñupiatun'},
  {'id': 'io', 'title': 'Ido', 'nativeTitle': 'Ido'},
  {'id': 'is', 'title': 'Icelandic', 'nativeTitle': 'Íslenska'},
  {'id': 'it', 'title': 'Italian', 'nativeTitle': 'Italiano'},
  {'id': 'iu', 'title': 'Inuktitut', 'nativeTitle': 'ᐃᓄᒃᑎᑐᑦ'},
  {'id': 'ja', 'title': 'Japanese', 'nativeTitle': '日本語 (にほんご／にっぽんご)'},
  {'id': 'jv', 'title': 'Javanese', 'nativeTitle': 'basa Jawa'},
  {'id': 'kl', 'title': 'Kalaallisut, Greenlandic', 'nativeTitle': 'kalaallisut, kalaallit oqaasii'},
  {'id': 'kn', 'title': 'Kannada', 'nativeTitle': 'ಕನ್ನಡ'},
  {'id': 'kr', 'title': 'Kanuri', 'nativeTitle': 'Kanuri'},
  {'id': 'ks', 'title': 'Kashmiri', 'nativeTitle': 'कश्मीरी, كشميري‎'},
  {'id': 'kk', 'title': 'Kazakh', 'nativeTitle': 'Қазақ тілі'},
  {'id': 'km', 'title': 'Khmer', 'nativeTitle': 'ភាសាខ្មែរ'},
  {'id': 'ki', 'title': 'Kikuyu, Gikuyu', 'nativeTitle': 'Gĩkũyũ'},
  {'id': 'rw', 'title': 'Kinyarwanda', 'nativeTitle': 'Ikinyarwanda'},
  {'id': 'ky', 'title': 'Kirghiz, Kyrgyz', 'nativeTitle': 'кыргыз тили'},
  {'id': 'kv', 'title': 'Komi', 'nativeTitle': 'коми кыв'},
  {'id': 'kg', 'title': 'Kongo', 'nativeTitle': 'KiKongo'},
  {'id': 'ko', 'title': 'Korean', 'nativeTitle': '한국어 (韓國語), 조선말 (朝鮮語)'},
  {'id': 'ku', 'title': 'Kurdish', 'nativeTitle': 'Kurdî, كوردی‎'},
  {'id': 'kj', 'title': 'Kwanyama, Kuanyama', 'nativeTitle': 'Kuanyama'},
  {'id': 'la', 'title': 'Latin', 'nativeTitle': 'latine, lingua latina'},
  {'id': 'lb', 'title': 'Luxembourgish, Letzeburgesch', 'nativeTitle': 'Lëtzebuergesch'},
  {'id': 'lg', 'title': 'Luganda', 'nativeTitle': 'Luganda'},
  {'id': 'li', 'title': 'Limburgish, Limburgan, Limburger', 'nativeTitle': 'Limburgs'},
  {'id': 'ln', 'title': 'Lingala', 'nativeTitle': 'Lingála'},
  {'id': 'lo', 'title': 'Lao', 'nativeTitle': 'ພາສາລາວ'},
  {'id': 'lt', 'title': 'Lithuanian', 'nativeTitle': 'lietuvių kalba'},
  {'id': 'lu', 'title': 'Luba-Katanga', 'nativeTitle': ''},
  {'id': 'lv', 'title': 'Latvian', 'nativeTitle': 'latviešu valoda'},
  {'id': 'gv', 'title': 'Manx', 'nativeTitle': 'Gaelg, Gailck'},
  {'id': 'mk', 'title': 'Macedonian', 'nativeTitle': 'македонски јазик'},
  {'id': 'mg', 'title': 'Malagasy', 'nativeTitle': 'Malagasy fiteny'},
  {'id': 'ms', 'title': 'Malay', 'nativeTitle': 'bahasa Melayu, بهاس ملايو‎'},
  {'id': 'ml', 'title': 'Malayalam', 'nativeTitle': 'മലയാളം'},
  {'id': 'mt', 'title': 'Maltese', 'nativeTitle': 'Malti'},
  {'id': 'mi', 'title': 'Māori', 'nativeTitle': 'te reo Māori'},
  {'id': 'mr', 'title': 'Marathi (Marāṭhī)', 'nativeTitle': 'मराठी'},
  {'id': 'mh', 'title': 'Marshallese', 'nativeTitle': 'Kajin M̧ajeļ'},
  {'id': 'mn', 'title': 'Mongolian', 'nativeTitle': 'монгол'},
  {'id': 'na', 'title': 'Nauru', 'nativeTitle': 'Ekakairũ Naoero'},
  {'id': 'nv', 'title': 'Navajo, Navaho', 'nativeTitle': 'Diné bizaad, Dinékʼehǰí'},
  {'id': 'nb', 'title': 'Norwegian Bokmål', 'nativeTitle': 'Norsk bokmål'},
  {'id': 'nd', 'title': 'North Ndebele', 'nativeTitle': 'isiNdebele'},
  {'id': 'ne', 'title': 'Nepali', 'nativeTitle': 'नेपाली'},
  {'id': 'ng', 'title': 'Ndonga', 'nativeTitle': 'Owambo'},
  {'id': 'nn', 'title': 'Norwegian Nynorsk', 'nativeTitle': 'Norsk nynorsk'},
  {'id': 'no', 'title': 'Norwegian', 'nativeTitle': 'Norsk'},
  {'id': 'ii', 'title': 'Nuosu', 'nativeTitle': 'ꆈꌠ꒿ Nuosuhxop'},
  {'id': 'nr', 'title': 'South Ndebele', 'nativeTitle': 'isiNdebele'},
  {'id': 'oc', 'title': 'Occitan', 'nativeTitle': 'Occitan'},
  {'id': 'oj', 'title': 'Ojibwe, Ojibwa', 'nativeTitle': 'ᐊᓂᔑᓈᐯᒧᐎᓐ'},
  {'id': 'cu',
  'title': 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', 'nativeTitle': 'ѩзыкъ словѣньскъ'},
  {'id': 'om', 'title': 'Oromo', 'nativeTitle': 'Afaan Oromoo'},
  {'id': 'or', 'title': 'Oriya', 'nativeTitle': 'ଓଡ଼ିଆ'},
  {'id': 'os', 'title': 'Ossetian, Ossetic', 'nativeTitle': 'ирон æвзаг'},
  {'id': 'pa', 'title': 'Panjabi, Punjabi', 'nativeTitle': 'ਪੰਜਾਬੀ, پنجابی‎'},
  {'id': 'pi', 'title': 'Pāli', 'nativeTitle': 'पाऴि'},
  {'id': 'fa', 'title': 'Persian', 'nativeTitle': 'فارسی'},
  {'id': 'pl', 'title': 'Polish', 'nativeTitle': 'polski'},
  {'id': 'ps', 'title': 'Pashto, Pushto', 'nativeTitle': 'پښتو'},
  {'id': 'pt', 'title': 'Portuguese', 'nativeTitle': 'Português'},
  {'id': 'qu', 'title': 'Quechua', 'nativeTitle': 'Runa Simi, Kichwa'},
  {'id': 'rm', 'title': 'Romansh', 'nativeTitle': 'rumantsch grischun'},
  {'id': 'rn', 'title': 'Kirundi', 'nativeTitle': 'kiRundi'},
  {'id': 'ro', 'title': 'Romanian, Moldavian, Moldovan', 'nativeTitle': 'română'},
  {'id': 'ru', 'title': 'Russian', 'nativeTitle': 'русский язык'},
  {'id': 'sa', 'title': 'Sanskrit (Saṁskṛta)', 'nativeTitle': 'संस्कृतम्'},
  {'id': 'sc', 'title': 'Sardinian', 'nativeTitle': 'sardu'},
  {'id': 'sd', 'title': 'Sindhi', 'nativeTitle': 'सिन्धी, سنڌي، سندھی‎'},
  {'id': 'se', 'title': 'Northern Sami', 'nativeTitle': 'Davvisámegiella'},
  {'id': 'sm', 'title': 'Samoan', 'nativeTitle': 'gagana faa Samoa'},
  {'id': 'sg', 'title': 'Sango', 'nativeTitle': 'yângâ tî sängö'},
  {'id': 'sr', 'title': 'Serbian', 'nativeTitle': 'српски језик'},
  {'id': 'gd', 'title': 'Scottish Gaelic; Gaelic', 'nativeTitle': 'Gàidhlig'},
  {'id': 'sn', 'title': 'Shona', 'nativeTitle': 'chiShona'},
  {'id': 'si', 'title': 'Sinhala, Sinhalese', 'nativeTitle': 'සිංහල'},
  {'id': 'sk', 'title': 'Slovak', 'nativeTitle': 'slovenčina'},
  {'id': 'sl', 'title': 'Slovene', 'nativeTitle': 'slovenščina'},
  {'id': 'so', 'title': 'Somali', 'nativeTitle': 'Soomaaliga, af Soomaali'},
  {'id': 'st', 'title': 'Southern Sotho', 'nativeTitle': 'Sesotho'},
  {'id': 'es', 'title': 'Spanish; Castilian', 'nativeTitle': 'español, castellano'},
  {'id': 'su', 'title': 'Sundanese', 'nativeTitle': 'Basa Sunda'},
  {'id': 'sw', 'title': 'Swahili', 'nativeTitle': 'Kiswahili'},
  {'id': 'ss', 'title': 'Swati', 'nativeTitle': 'SiSwati'},
  {'id': 'sv', 'title': 'Swedish', 'nativeTitle': 'svenska'},
  {'id': 'ta', 'title': 'Tamil', 'nativeTitle': 'தமிழ்'},
  {'id': 'te', 'title': 'Telugu', 'nativeTitle': 'తెలుగు'},
  {'id': 'tg', 'title': 'Tajik', 'nativeTitle': 'тоҷикӣ, toğikī, تاجیکی‎'},
  {'id': 'th', 'title': 'Thai', 'nativeTitle': 'ไทย'},
  {'id': 'ti', 'title': 'Tigrinya', 'nativeTitle': 'ትግርኛ'},
  {'id': 'bo', 'title': 'Tibetan Standard, Tibetan, Central', 'nativeTitle': 'བོད་ཡིག'},
  {'id': 'tk', 'title': 'Turkmen', 'nativeTitle': 'Türkmen, Түркмен'},
  {'id': 'tl', 'title': 'Tagalog', 'nativeTitle': 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔'},
  {'id': 'tn', 'title': 'Tswana', 'nativeTitle': 'Setswana'},
  {'id': 'to', 'title': 'Tonga (Tonga Islands)', 'nativeTitle': 'faka Tonga'},
  {'id': 'tr', 'title': 'Turkish', 'nativeTitle': 'Türkçe'},
  {'id': 'ts', 'title': 'Tsonga', 'nativeTitle': 'Xitsonga'},
  {'id': 'tt', 'title': 'Tatar', 'nativeTitle': 'татарча, tatarça, تاتارچا‎'},
  {'id': 'tw', 'title': 'Twi', 'nativeTitle': 'Twi'},
  {'id': 'ty', 'title': 'Tahitian', 'nativeTitle': 'Reo Tahiti'},
  {'id': 'ug', 'title': 'Uighur, Uyghur', 'nativeTitle': 'Uyƣurqə, ئۇيغۇرچە‎'},
  {'id': 'uk', 'title': 'Ukrainian', 'nativeTitle': 'українська'},
  {'id': 'ur', 'title': 'Urdu', 'nativeTitle': 'اردو'},
  {'id': 'uz', 'title': 'Uzbek', 'nativeTitle': 'zbek, Ўзбек, أۇزبېك‎'},
  {'id': 've', 'title': 'Venda', 'nativeTitle': 'Tshivenḓa'},
  {'id': 'vi', 'title': 'Vietnamese', 'nativeTitle': 'Tiếng Việt'},
  {'id': 'vo', 'title': 'Volapük', 'nativeTitle': 'Volapük'},
  {'id': 'wa', 'title': 'Walloon', 'nativeTitle': 'Walon'},
  {'id': 'cy', 'title': 'Welsh', 'nativeTitle': 'Cymraeg'},
  {'id': 'wo', 'title': 'Wolof', 'nativeTitle': 'Wollof'},
  {'id': 'fy', 'title': 'Western Frisian', 'nativeTitle': 'Frysk'},
  {'id': 'xh', 'title': 'Xhosa', 'nativeTitle': 'isiXhosa'},
  {'id': 'yi', 'title': 'Yiddish', 'nativeTitle': 'ייִדיש'},
  {'id': 'yo', 'title': 'Yoruba', 'nativeTitle': 'Yorùbá'},
  {'id': 'za', 'title': 'Zhuang, Chuang', 'nativeTitle': 'Saɯ cueŋƅ, Saw cuengh'}
];
