name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache hosting build
        uses: actions/cache@v4
        id: cache-hosting
        with:
          key: ${CI_COMMIT_REF_SLUG}
          path: |
            ./hosting/node_modules/
            ./hosting/.next/cache/

      - run: npm ci && npm run build
        working-directory: ./hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TANAM_TESTING }}
          channelId: live
          projectId: tanam-testing
