name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: |
            hosting/package-lock.json

      - name: Install global NPM tools
        run: |
          npm install -g firebase-tools@latest

      - name: Cache hosting build
        uses: actions/cache@v4
        id: cache-hosting
        with:
          key: ${CI_COMMIT_REF_SLUG}
          path: |
            ./hosting/node_modules/
            ./hosting/.next/cache/

      - name: Build application
        run: npm ci && npm run build
        working-directory: ./hosting

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hosting
          path: ./hosting/.next/
          retention-days: 2

  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: |
            hosting/package-lock.json

      - name: Install global NPM tools
        run: |
          npm install -g firebase-tools@latest

      - name: Install hosting dependencies
        run: npm ci
        working-directory: ./hosting

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: hosting

      - uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TANAM_TESTING }}
          projectId: tanam-testing
          channelId: live
